// <auto-generated />
namespace EF_first_approach_demo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class editColumn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(editColumn));
        
        string IMigrationMetadata.Id
        {
            get { return "202310030806552_editColumn"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
